### PR TITLE
Improve button visuals

### PR DESCRIPTION
**Pull request by max**
Thanks for creating deploy.now.sh. I'm glad someone is carrying on the legacy of the "Heroku Button". 👊

This PR improves the visuals fo the Deploy to now button to better match the context in which it's most likely being used: A Github repo.

screen shot 2017-01-25 at 1 32 58 pm

screen shot 2017-01-25 at 1 41 47 pm

## Rounded corners

- Match other common repo badges and general GitHub aesthetic (rounded corners everywhere – see the README screenshot).
- Rounded corners on buttons make them look friendlier. Real world metaphor: You don't sit on pointy stuff but look for smooth edges.

## Logo

- There are various zeit/now logos available on the site and the small gradient makes the button stand out just a little bit more.

## Wording

- The typeface is now properly kerned
- Emphasis with color and font weight is put on Deploy and now
- Spacing and dimensions tweaked to fit overall button layout

### CODE REVIEW

**Comment by amccloud** [comment]
@max this looks awesome!

**Comment by timothyis** [comment]
@max Perhaps the button could have no border-radius to keep inline with ZEIT's styling preferences? 😄 I think that'd help with recognition of the brand.

**Comment by max** [comment]
@CodeTheory I contemplated this as well. But I think that the context in which the button is going to be shown (Github) matters more than the brand consistency. This button will likely never show up on an actual zeit.co page. As far as recognition of the brand goes I think the fact that the button prominently shows the icon and the label includes the brand name I'm not sure how much the rounded corners would actually add.

I would also argue that zeit.co's buttons should be round cc @rauchg (square buttons are too easily confused with input fields). But that's clearly not my place to comment on. 🙊

**Comment by max** [comment]
Here they are side by side:

screen shot 2017-01-25 at 3 59 44 pm

**Comment by timothyis** [comment]
You make very good points!
I do think the square button looks better because it matches ZEIT's style, though.
Perhaps @evilrabbit could comment more!

**Comment by zpnk** [comment]
@max This is seriously fantastic. Far better than the original - I love it! Thanks for taking the time for work on this and also write up the reasoning behind it. I enjoyed understanding your thought process. 

On the topic of rounded corners-vs-square, I agree with you that the rounded corners match the GitHub context much better and just plain look better as a button. Especially after seeing them side-by-side, I support keeping the rounded corners.

I'm curious, did you design the Heroku button?

**Comment by max** [comment]
@zpnk I did. Obviously with such a feature there are always many people involved (@zeke – app.json, and @dizzyup – Heroku Dashboard).

**Comment by zpnk** [comment]
@max That's awesome. Pretty cool to get a PR from the *original* deploy button designer. 😄  

Merging this now!

**Comment by evilrabbit** [comment]
Nice button @max ! 💕

**Comment by zeke** [comment]
🤘

**Pull request merged**
